name: tunele-api-prod

services:
  api:
    image: ghcr.io/alneng/tunele-api:latest # This will be replaced by CI/CD
    container_name: tunele-api
    restart: unless-stopped
    ports:
      - "7600:7600"
    volumes:
      - ./logs/prod:/app/logs
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - tunele-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7600/api/health"]
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: tunele-redis-prod
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    networks:
      - tunele-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  tunele-network:
    driver: bridge