services:
  tunele-api:
    container_name: tunele
    image: tunele-api
    env_file: ".env"
    build:
      context: ../../
      dockerfile: ./src/backend/Dockerfile
    ports:
      - "7600:7600"
    restart: unless-stopped
    networks:
      - tunele-network
    volumes:
      - ./logs:/app/logs

networks:
  tunele-network:
    driver: bridge
