apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tunele-preview

resources:
  - ../../base
  - ingressroute.yaml

images:
  - name: ghcr.io/alneng/tunele-api
    newTag: preview
